In [124]:
 # NUMPY ASSIGHNMENT




import numpy as np

# Question 1

a = np.random.randint(10,50,20)
mean = np.mean(a)
std_dev = np.std(a)
sum_a = np.sum(a)
print(a)
print("Mean = ",mean)
print("Standard Deviation = ",std_dev)


[23 40 11 16 10 45 26 12 21 20 21 33 30 39 39 21 43 22 28 42]
Mean =  27.1
Standard Deviation =  10.949429208867466


In [123]:
# Question 2 

a = np.random.rand(6,5)
b = a.reshape(5,6)
print ("6 * 5 = ",a)
print ("5 * 6 =  ",b)

6 * 5 =  [[0.41292353 0.85606337 0.9547912  0.21692425 0.71611025]
 [0.34689893 0.40807023 0.57976833 0.41695095 0.87969554]
 [0.47845633 0.50441358 0.96718456 0.25708041 0.60777277]
 [0.98546669 0.56773973 0.39014408 0.92492962 0.11438666]
 [0.07051848 0.54921089 0.80356563 0.2922425  0.16915651]
 [0.63306808 0.79564517 0.52656841 0.55745719 0.35552238]]
5 * 6 =   [[0.41292353 0.85606337 0.9547912  0.21692425 0.71611025 0.34689893]
 [0.40807023 0.57976833 0.41695095 0.87969554 0.47845633 0.50441358]
 [0.96718456 0.25708041 0.60777277 0.98546669 0.56773973 0.39014408]
 [0.92492962 0.11438666 0.07051848 0.54921089 0.80356563 0.2922425 ]
 [0.16915651 0.63306808 0.79564517 0.52656841 0.55745719 0.35552238]]


In [121]:
# Question 3

a = np.arange(1,26).reshape(5,5)
b = a[2:5, 1:4]
print("Main array:\n",a)
print ("Sub array:\n",b)
       


Main array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Sub array:
 [[12 13 14]
 [17 18 19]
 [22 23 24]]


In [122]:
# Question 4

a = np.random.randint(1,101,10)
b = np.random.randint(1,101,10)
c = (a+b)
d = (a+b)*2
print("Random Array 1",a)
print("Random Array 2",b)
print("Array 1 + Array 2 ",c)
print("(Array 1 + Array 2)*2 ",d)

Random Array 1 [70 99 99 71 57 74 37 57 88 20]
Random Array 2 [43  7 54 20 55 91 64 33 74 87]
Array 1 + Array 2  [113 106 153  91 112 165 101  90 162 107]
(Array 1 + Array 2)*2  [226 212 306 182 224 330 202 180 324 214]


In [138]:
# Question 5

a = np.random.randint(1,11,(3,4))
b = np.array([1,2,3,4])
c = a+b

print("2D Array 'A':\n",a)

print("1D Array 'B':\n",b)

print("(A+B):\n",c)
print("In NumPy, broadcasting allows arrays of different shapes to be combined in arithmetic operations.\n When you add a 1D array B of shape (4,) to a 2D array A of shape (3, 4),\n NumPy automatically 'broadcasts' the 1D array B to match the shape of A along the appropriate dimension.")


2D Array 'A':
 [[8 2 6 8]
 [5 5 1 9]
 [7 6 9 1]]
1D Array 'B':
 [1 2 3 4]
(A+B):
 [[ 9  4  9 12]
 [ 6  7  4 13]
 [ 8  8 12  5]]
In NumPy, broadcasting allows arrays of different shapes to be combined in arithmetic operations.
 When you add a 1D array B of shape (4,) to a 2D array A of shape (3, 4),
 NumPy automatically 'broadcasts' the 1D array B to match the shape of A along the appropriate dimension.


In [156]:
# Question 6 

a = np.random.randint(1,101,(3,3))
b = np.sum(a,axis=1)
c = np.argmax(b)
max_sum_row = a[c]
max_value = np.max(max_sum_row)

print ("Matrix :\n",a)
print ("Sum of each row:",b)
print("Row with max sum",max_sum_row)
print ("Max value in that row",max_value)

Matrix :
 [[15 76 78]
 [91 30 26]
 [20 60 67]]
Sum of each row: [169 147 147]
Row with max sum [15 76 78]
Max value in that row 78


In [163]:
# Question 7

a = np.random.randint(1,10,(2,2))
b = np.random.randint(1,10,(2,2))
c= np.dot(a,b)
print("Matrix A:\n",a)
print("Matrix B:\n",b)
print("Matrix Multiplication\n:",c)

Matrix A:
 [[6 5]
 [4 5]]
Matrix B:
 [[3 6]
 [3 7]]
Matrix Multiplication
: [[33 71]
 [27 59]]


In [166]:
# Question 8

a = np.random.randint(1,50,(6,6))
b = a[a>25]

print("Array:\n",a)
print("Greater than 25:\n",b)

Array:
 [[36 37 23 40 15  3]
 [37 36 15 31 11  5]
 [47 30 40 27 46  8]
 [19 19  3 48 45 14]
 [31 46 13 31 28 35]
 [46 24 47 45  5 12]]
Greater than 25:
 [36 37 40 37 36 31 47 30 40 27 46 48 45 31 46 31 28 35 46 47 45]


In [181]:
# Question 9

a = np.random.rand(5,5)
median_row = np.median(a,axis=1)
median_coloum = np.median(a,axis=0)

variance_row = np.var(a,axis=1)
variance_coloum = np.var(a,axis=1)

print("5*5:\n",a)
print ("Row median:",median_row)
print ("Coloum median :",median_coloum)
print("variance coloum :",variance_coloum)
print("variance row:",variance_row)

5*5:
 [[0.12343745 0.8745065  0.0597403  0.81944938 0.49920102]
 [0.48077591 0.95930192 0.31357043 0.21879121 0.28147059]
 [0.59180157 0.37066402 0.44569116 0.1386031  0.69460968]
 [0.0231157  0.81107423 0.49965631 0.64500842 0.33448359]
 [0.49199539 0.03349621 0.02081601 0.28092341 0.49914878]]
Row median: [0.49920102 0.31357043 0.44569116 0.49965631 0.28092341]
Coloum median : [0.48077591 0.81107423 0.31357043 0.28092341 0.49914878]
variance coloum : [0.1149746  0.07216105 0.0366415  0.07312811 0.04396511]
variance row: [0.1149746  0.07216105 0.0366415  0.07312811 0.04396511]


In [188]:
# Question 10

a = np.random.randint(1,10,(3,3))
sub_a = a -2
sqr_a = a ** 2
a = np.reciprocal(a.astype(float))

print ("Matrix : \n",a)
print ("Subtracted Matrix :\n", sub_a)
print ("Squared Matrix :\n",sqr_a)
print ("Reciprocal of Matrix :\n",a)

Matrix : 
 [[0.125      0.33333333 0.125     ]
 [1.         0.25       0.2       ]
 [0.25       0.11111111 0.14285714]]
Subtracted Matrix :
 [[ 6  1  6]
 [-1  2  3]
 [ 2  7  5]]
Squared Matrix :
 [[64  9 64]
 [ 1 16 25]
 [16 81 49]]
Reciprocal of Matrix :
 [[0.125      0.33333333 0.125     ]
 [1.         0.25       0.2       ]
 [0.25       0.11111111 0.14285714]]


In [9]:
# PANDAS ASSIGNMENT




# Question 1


import pandas as pd

df = pd.read_csv("auto-mpg.csv")
print (df.head(10))
print(f"total rows {df.shape[0]},Total coloum {df.shape[1]}")
print(df.describe())




    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skyla

In [26]:
# Question 2


filtered_car = df[(df["model year"] == 75) & (df["weight"] <3000)]
filtered = filtered_car[["car name","weight", "mpg"]]

print (filtered)

              car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0


In [33]:
# Question 3


df["horsepower"]= pd.to_numeric(df["horsepower"],errors = "coerce")
df.loc[:,"horsepower"].fillna(df["horsepower"].median())
print(df.isnull().sum())



mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64


In [37]:
# Question 4


df["power_to_weight_ratio"] = df["horsepower"] / df["weight"]
print(df.head())

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model year  origin                   car name  power-to weight_ratio  \
0          70       1  chevrolet chevelle malibu               0.037100   
1          70       1          buick skylark 320               0.044679   
2          70       1         plymouth satellite               0.043655   
3          70       1              amc rebel sst               0.043694   
4          70       1                ford torino               0.040591   

   power_to_weight_ratio  
0               0.037100  
1               0.044679  
2               0.043655  
3               0.04

In [41]:
# Question 5

mean = df.groupby("origin")["mpg"].mean()

print(mean)

                               

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64


In [43]:
# Question 6

top = df.sort_values(by= "mpg",ascending = False).head(10)

print(top)

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
322  46.6          4          86.0        65.0    2110          17.9   
329  44.6          4          91.0        67.0    1850          13.8   
325  44.3          4          90.0        48.0    2085          21.7   
394  44.0          4          97.0        52.0    2130          24.6   
326  43.4          4          90.0        48.0    2335          23.7   
244  43.1          4          90.0        48.0    1985          21.5   
309  41.5          4          98.0        76.0    2144          14.7   
330  40.9          4          85.0         NaN    1835          17.3   
324  40.8          4          85.0        65.0    2110          19.2   
247  39.4          4          85.0        70.0    2070          18.6   

     model year  origin                         car name  \
322          80       3                        mazda glc   
329          80       3              honda civic 1500 gl   
325          80       2    

In [50]:
# Question 7

def performance_score(row):
    return row["mpg"]* row["acceleration"] / row["weight"]

df["performance_score"] = df.apply(a,axis = 1)
print(df.head())

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model year  origin                   car name  power-to weight_ratio  \
0          70       1  chevrolet chevelle malibu               0.037100   
1          70       1          buick skylark 320               0.044679   
2          70       1         plymouth satellite               0.043655   
3          70       1              amc rebel sst               0.043694   
4          70       1                ford torino               0.040591   

   power_to_weight_ratio         a  performance  performance_score  
0               0.037100  0.061644     0.061644           0

In [49]:
# Question 8

summary = df.groupby("model year").agg({
    "mpg":"mean",
    "weight":"mean",
    "horsepower":"mean"
}).reset_index()

print(summary)
    
                                          

    model year        mpg       weight  horsepower
0           70  17.689655  3372.793103  147.827586
1           71  21.250000  2995.428571  107.037037
2           72  18.714286  3237.714286  120.178571
3           73  17.100000  3419.025000  130.475000
4           74  22.703704  2877.925926   94.230769
5           75  20.266667  3176.800000  101.066667
6           76  21.573529  3078.735294  101.117647
7           77  23.375000  2997.357143  105.071429
8           78  24.061111  2861.805556   99.694444
9           79  25.093103  3055.344828  101.206897
10          80  33.696552  2436.655172   77.481481
11          81  30.334483  2522.931034   81.035714
12          82  31.709677  2453.548387   81.466667


In [51]:
# Question 9

high_mpg_cars = df[df["mpg"]>30][["mpg","cylinders", "horsepower","weight"]]
high_mpg_cars.to_csv("high_mpg_cars.csv",index = False)



In [54]:
# Question 10

q1 = df["mpg"].quantile(0.25)
q3 = df["mpg"].quantile(0.75)
iqr = q3-q1

outliers = df[(df["mpg"] <(q1- 1.5 * iqr)) | (df["mpg"] >(q3+1.5* iqr))]
outliers_df = outliers[["car name","mpg", "model year"]]
print(outliers_df)

      car name   mpg  model year
322  mazda glc  46.6          80
